from datetime import datetime


def _protection_plan(maintenance_type: str) -> list:
    plan = {
        "Track Maintenance": [
            "Flagman posted at advance warning points both directions",
            "Detonators laid at 600 m and 1200 m on approach sides",
            "Permissible speed 65 kmph for trains run through to first overlap",
            "Track circuit cut during possession; manual block operation",
        ],
        "Signal Maintenance": [
            "Block signalling equipment isolated and grounded",
            "Manual block working authorized by Station Master",
            "Pilotman accompanied on single-line section",
        ],
        "Electrical Maintenance": [
            "OHE isolated and earthed at both traction substation ends",
            "Return conductor continuity established before train movement",
            "Working with priority to overhead equipment gang",
        ],
        "Bridge Inspection": [
            "Traffic suspended through affiliated girder",
            "Platform-controlled auxiliary movement past site",
            "Minimum 2 personnel for confined space entry",
        ],
    }
    return plan.get(maintenance_type, [
        "Flagman and detonator protection per General Rules 2005",
        "Inspection authority to authorize movement past point",
    ])


def _resources_summary(req) -> str:
    parts = []
    if getattr(req, "crew_size", None):
        parts.append(f"Crew: {req.crew_size} personnel")
    if getattr(req, "equipment", None):
        parts.append(f"Equipment: {req.equipment}")
    if getattr(req, "track_no", None):
        parts.append(f"Track/Line: {req.track_no}")
    return "; ".join(parts) if parts else "As per block working programme"


def generate_block_notice(plan, req, officer_name: str = "Concerned Officer") -> str:
    now = datetime.utcnow()
    wtype = getattr(req, "work_type", None) or ""
    weather = getattr(req, "weather_sensitive", None) or "NO"
    protection = _protection_plan(req.maintenance_type)

    lines = [
        "=" * 78,
        "               RAIL BLOCK PERMISSION / WRITTEN PERMISSION NOTICE",
        "=" * 78,
        f"Block No:           {plan.block_id}",
        f"Division:           Pune (Central Railway)",
        f"Date:               {plan.proposed_date}",
        f"Section:            {req.section}",
        f"From Station/Point: {req.location}",
        f"Track/Line:         {getattr(req, 'track_no', None) or 'Both lines as applicable'}",
        f"Block Commencing:   {plan.start_time} IST",
        f"Block Ending:       {plan.end_time} IST",
        f"Total Block Time:   {plan.duration_minutes} minutes",
        "",
        f"Nature of Work:     {req.maintenance_type} | {wtype or 'As per programme'}",
        f"Resources Deployed: {_resources_summary(req)}",
        f"Weather Sensitive:  {weather}",
        "",
        "Protection Arrangements:",
    ]
    for i, p in enumerate(protection, 1):
        lines.append(f"  {i}. {p}")

    lines.extend([
        "",
        "Danger Area / Speed Restriction:",
        f"  Speed restricted to 30 kmph over the work site with 1000 m caution",
        f"  applicable to all trains running on the affected track.",
        "",
        "Remarks:",
        "  1. This block is sanctioned subject to safety rules of the 'General & Subsidiary' Rules.",
        "  2. Work to be indicated as per 'Engineering Works' time-table notice.",
        "  3. Possession of track line taken and released as per endorsement below.",
        "  4. Backup power & lighting to be arranged by the Engineering department.",
        "",
        f"Authority & Sanction: {officer_name}",
        f"Generated By:        RailLink AI  |  Generated At: {now.strftime('%Y-%m-%d %H:%M:%S')} UTC",
        "-" * 78,
        "ENDORSEMENTS",
        "  Taken over by Engineer (name/sign):  ________________________    Time: ________",
        "  Track line released by Engineer:      ________________________    Time: ________",
        "  Received by Station Master:           ________________________    Time: ________",
        "=" * 78,
    ])
    return "\n".join(lines)


def generate_caution_order(plan, req, sequence: int = 1) -> str:
    now = datetime.utcnow()
    lines = [
        "=" * 60,
        "                       CAUTION ORDER (FORM T-409)",
        f"  Caution Order No:     {sequence:04d}",
        f"  Issued:              {plan.proposed_date} {plan.start_time} for {req.section}",
        f"  Block No:            {plan.block_id}",
        "-" * 60,
        f"  All trains passing over the section between {req.location} and {req.section}",
        f"  shall run at 30 kmph with caution during {plan.start_time} and {plan.end_time}.",
        "  Reason: Engineering works / OHE maintenance in progress under block.",
        "",
        "  Driver to:",
        "    1. Approach the work site with extreme caution.",
        "    2. Be prepared to stop short of any obstruction / flagman signals.",
        "    3. Proceed only after receiving the clear signal from flagman.",
        "",
        f"  Issued by:  Station Master / Block Issuing Authority   {now.strftime('%Y-%m-%d %H:%M')}",
        "=" * 60,
    ]
    return "\n".join(lines)


def generate_artifacts(plan, req, officer_name: str = "Concerned Officer") -> dict:
    return {
        "block_notice": generate_block_notice(plan, req, officer_name),
        "caution_order": generate_caution_order(plan, req),
    }